### ISSUE TITLE
Unknown CEM error

### ISSUE THREAD

**Issue by Drekith-1** [vtl/volvo-cem-cracker#25]
Hi. New here first off I’m not a programmer or anything just a fairly tech savvy handsy guy with too much free time. Anyway I’ve followed the schematics for the lcd version using a teensy 4.0 
However when I try to decode the cem the lcd displays unknown cem exiting……..

I’ve triple checked my connections are quality and true to the schematic as well as reloading the software onto the teensy a few times yet I get the same error. Is it likely I’ve just done something wrong or is it just not possible with my cem. 

V50 2007/2008 D5 facelift

**Comment by vtl** [comment]
https://github.com/cmolson/volvo-cem-cracker/tree/one_pass

**Comment by Drekith-1** [comment]
Worked a treat. Another successful read thanks guys 👌 drls are finally now off via vdash. 
![IMG_3820](https://github.com/vtl/volvo-cem-cracker/assets/165218644/ae0e0161-aa5b-40a0-8b87-58d6d927a420)
