### ISSUE TITLE
Pinouts for bench people

### ISSUE THREAD

**Issue by Unwrath** [vtl/volvo-cem-cracker#6]
Hey, it's not an issue, but rather a request - maybe you could post pinouts for other people of CEM's on the bench?
And is there a chance that you have mapped which pins need to be connected to brick shaped ones?
Thanks!

**Comment by vtl** [comment]
It was posted on the forum: https://www.matthewsvolvosite.com/forums/viewtopic.php?f=10&t=85611&start=890

**Comment by Unwrath** [comment]
Yes I saw that, but sadly that's for P1's . Any chance you have pinouts for P2? 9452553

**Comment by vtl** [comment]
P2 -04 CEMs are not susceptible to that attack.

**Comment by Unwrath** [comment]
okay.. how come it's in the list (in source file)?

**Comment by vtl** [comment]
This is work in progress (without any actual progress done).
